"""
CONSTANTS

Defines here each constant that will be needed and used. 
"""
# -----------------------------------------------------
# Scripting Constants
# -----------------------------------------------------

from casting.color import Color
GAME_NAME = "Shipwreck"

# SHIP AMOUNT PER LEVEL
LEVEL_1_AMOUNT = (0, 2, 4)
LEVEL_2_AMOUNT = (4, 4, 6)
BOSS_LEVEL_AMOUNT = (2, 0 ,0)

# DIRECTIONS
MOVE_BACKWARDS_P1 = "a"
MOVE_FORWARDS_P1 = "d"
MOVE_UP_P1 = "w"
MOVE_DOWN_P1 = "s"
ENTER = "enter"
PAUSE = "p"

# SCENES
LEVEL_GROUP = "Levels"
NEW_GAME = 1
NEXT_LEVEL = 2
BOSS_LEVEL = 3
TRY_AGAIN = 4
IN_PLAY = 5
GAME_OVER = 6


# BEHIND THE SCENES STAGES
INITIALIZE = 0 
LOAD = 1
INPUT = 2
UPDATE = 3
OUTPUT = 4
UNLOAD = 5
RELEASE = 6


# VIDEO
MAX_X = None
MAX_Y = None
HUD_MARGIN = 15

# PLAYER SHIP
SHIP_GROUP = "Ship"
# Insert Ship Image Here v
SHIP_IMAGE = ""
SHIP_WIDTH = 56
SHIP_HEIGHT = 56
SHIP_VELOCITY = 7

# ENEMY SHIP
HEAVY_ENEMY_SHIP_GROUP = "Heavy Enemy Ships"
MEDIUM_ENEMY_SHIP_GROUP = "Medium Enemy Ships"
LIGHT_ENEMY_SHIP_GROUP = "Light Enemy Ships"
MAX_AMMOUNT_OF_SHIPS = 36
HEAVY_ENEMY_SHIP_IMAGE = ""
MEDIUM_ENEMY_SHIP_IMAGE = ""
LIGHT_ENEMY_SHIP_IMAGE = ""

# LASERS
LASER_GROUP = "Laser"
LASER_HEAVY_DAMAGE = 8
LASER_MEDIUM_DAMAGE = 4
LASER_LIGHT_DAMAGE = 2 

# STATS
STATS_GROUP = "Stats"
LIVES_GROUP = "Lives"
SCORE_GROUP = "Score"
DIALOG_GROUP = "Dialogs"
LEVEL_FORMAT = "LEVEL: {}"
LIVES_FORMAT = "LIVES: {}"
SCORE_FORMAT = "SCORE: {}"
DEFAULT_LIVES = 20
MAXIMUM_LIVES = 40

# START BACKGROUND
BLACK = Color(0, 0, 0, )

# ALIGNMENT 
ALIGN_CENTER = 0 
ALIGN_LEFT = 1
ALIGN_RIGHT = 2

#FILE PATHS
FONT_FILE = "CSE_210-06/assets/Fonts/zorque.otf"
FONT_SMALL = 32
FONT_LARGE = 64

# SCREEN
SCREEN_WIDTH = 1040
SCREEN_HEIGHT = 680
CENTER_X = SCREEN_WIDTH / 2
CENTER_Y = SCREEN_HEIGHT / 2

# SOUNDS
HIT_SOUND = ""
GAME_OVER_SOUND = ""

# FIELD
FIELD_TOP = 60
FIELD_BOTTOM = SCREEN_HEIGHT
FIELD_LEFT = 0
FIELD_RIGHT = SCREEN_WIDTH